language: node_js
node_js:
  - "8"
jobs:
    include:
        stage: test
        script: bin/test.js
        stage: verify
        script: bin/verify.js
        stage: build distribution
        script: bin/dist.js
        stage: deploy
        script: skip
        deploy:
            provider: pages
            skip_cleanup: true
            github_token: $GITHUB_TOKEN
            local_dir: dist/
            on:
                branch: master